### ISSUE TITLE
Update script and Readme to run on Windows machines

### ISSUE THREAD

**Issue by BartekPog** [BartekPog/Messenger-analysis#10]
There have been reported issues with running the script on Windows machines. Investigate the issue and address it properly.

**Comment by BartekPog** [comment]
Installing the dependencies with no virtual environment has raised many errors. It is highly unrecommended so won't be investigated. 

Running the script in `conda` and `virtualenv` environments raises following error:
```bash
$ python messages_analysis.py
Generating plots
Traceback (most recent call last):
  File "messages_analysis.py", line 28, in <module>
    runFullAnalysis()
  File "messages_analysis.py", line 16, in runFullAnalysis
    generatePlots(data)
  File "C:\Users\Bart\code\Messenger-analysis\src\plots_generation.py", line 15, in generatePlots
    plotActivityOverTime(data, user=USER, save_dir=PLOTS_DIR, order=6)
  File "C:\Users\Bart\code\Messenger-analysis\src\plots.py", line 72, in plotActivityOverTime
    plotting["date_float"] = plotting["date"].values.astype(float)
ValueError: could not convert string to float: '2020-01-01'
```

It seems that the pandas library **does not parse the dates** properly. It should be Datetime and thus it shall be convertible to float.  

## To do
[ ] Update the script to force Datetime conversion
[ ] Ensure it is running properly on Windows
[ ] Ensure it is running properly on Ubuntu
